### ISSUE TITLE
Error: template d.ir.type.Type.accept cannot deduce (cf SDC reported issue)

### ISSUE THREAD

**Issue by timotheecour** [deadalnix/libd-llvm#17]
initially reported here: https://github.com/deadalnix/SDC/issues/88 but probably more relevant here:

./src/d/llvm/type.d(42): Error: template d.ir.type.Type.accept cannot deduce function from argument types !()(TypeGen), candidates are:

**Comment by deadalnix** [comment]
Wait, what ? On which version of DMD ?

**Comment by deadalnix** [comment]
Not relevant anymore, the whole type mechanism has been revamped.
