### ISSUE TITLE
Migrate to using MCJIT

### ISSUE THREAD

**Issue by schancel** [deadalnix/libd-llvm#19]
The current LLVM JIT is being deprecated in favor of MCJIT.   We need to update the source to use that.
- [ ] Create JIT'd module cache. 
   - [ ] JIT Current Module
   - [ ] Add to linked list of modules
   - [ ] Create a new module as the 'active' module for codegen
- [ ] Figure out how to generate a single object file from all the modules created.

**Comment by deadalnix** [comment]
Depreacted as in it is not in master anymore, so there is a sense of urgency on that one.

**Comment by schancel** [comment]
@deadalnix  I started the process of reading about MCJIT since I don't know how the old ExecutionEngine worked either.  It looks like the C interfaces are already set up as needed.

What exactly is the problem with just switching the execution engine to an MCJITCompiler backend?   It looks like you always delete the generated function at the end of the JIT anyways?

**Comment by schancel** [comment]
I see. So you cannot add additional code to a module once you have JIT'd anything?  Can we just make a new module that depends on dmodule from CodeGenPass.ctfe()?  Or will running things from the new module cause our main module to be frozen as well?

**Comment by schancel** [comment]
Julia language discussion about migrating to MCJIT for reference: https://github.com/JuliaLang/julia/issues/3922

**Comment by deadalnix** [comment]
"So you cannot add additional code to a module once you have JIT'd anything"

You nailed it :) I'm not sure what the solution is at this point. Will read the discussion for julia.

**Comment by deadalnix** [comment]
Also, mandatory link: http://blog.llvm.org/2013/07/using-mcjit-with-kaleidoscope-tutorial.html

**Comment by deadalnix** [comment]
Also, thank for looking into it, I really hadn't the bandwidth myself.

**Comment by schancel** [comment]
Yeah.  I feel you man.  I'll get this figured out.  Just need some time.

**Comment by schancel** [comment]
It sounds like we may need to setup a cache for JIT'd modules and string them all together as we go.  I'll take a closer look this over this next week though.  I was out of town last week :)

**Comment by schancel** [comment]
That Kaleidoscope tutorial looks pretty straightforward for what we need to do.   I'm not quite sure how those C++ methods map to C helpers, but I will take a look soon.

**Comment by schancel** [comment]
Deadalnix, we should chat about this again.  I'm looking at the code and it looks like the LLVM backend needs some significant refactoring in order to be able to swap out the modules as they're compiled.

**Comment by deadalnix** [comment]
OK, I'll be available tomorrow during the day on IRC. What do you think is the best approach ? At this point, you should know more than I do about that issue.

**Comment by deadalnix** [comment]
http://lists.cs.uiuc.edu/pipermail/llvm-announce/2015-February/000057.html

Bad news, we are now behind schedule.

**Comment by schancel** [comment]
Yeah.  That sucks.  I don't have a ton of time to work on this stuff right now though.   Every time I think I have an idea I run into a problem with how MCJIT operates.

**Comment by schancel** [comment]
Can you update the headers to include http://llvm.org/docs/doxygen/html/group__LLVMCCoreModule.html#gabffdc747c14d77b3eb89500adf4f269b

**Comment by schancel** [comment]
https://github.com/deadalnix/libd-llvm/pull/20

This is an egregious hack, but it should work.  I'm not sure why LLVMCloneModule is not linking properly to test yet though.  Maybe its' only in 3.6?

**Comment by schancel** [comment]
So, I'm pretty sure that PR will work.  However, I suspect it will be very slow.   I'm installing LLVM 3.6 right now since a function I want to use is only in that. 

I'll continue to investigate other options though.   Another quick-and-dirty option might be to fork() and use IPC to return the result of the CTFE.  This would abuse the copy-on-write nature of memory after a fork.

I think ultimately we want to make multiple modules and link them together though, statically link them before writing out the object file.

**Comment by schancel** [comment]
This should be fixed once #20 goes in.
